// <auto-generated />
using System;
using BorsaGPT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BorsaGPT.Api.Migrations
{
    [DbContext(typeof(BorsaGptDbContext))]
    [Migration("20251012213646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BorsaGPT.Api.Models.CandidateWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Analyzed")
                        .HasColumnType("boolean")
                        .HasColumnName("analyzed");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<decimal?>("FirstTransferAmountEth")
                        .HasColumnType("decimal(28,18)")
                        .HasColumnName("first_transfer_amount_eth");

                    b.Property<string>("FirstTransferToken")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("first_transfer_token");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id");

                    b.HasIndex("Analyzed")
                        .HasDatabaseName("ix_candidate_wallets_analyzed");

                    b.HasIndex("BlockNumber")
                        .HasDatabaseName("ix_candidate_wallets_block_number");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_candidate_wallets_detected_at");

                    b.HasIndex("WalletAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_wallets_wallet_address");

                    b.ToTable("candidate_wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
